name: Update EOD Cache (debug)

on:
  workflow_dispatch:
  schedule:
    - cron: "10 11 * * 1-5"   # 16:40 IST, Mon–Fri

jobs:
  update-eod:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          echo "Branch: $GITHUB_REF"
          pwd && ls -la
          echo "---- data ----" && ls -la data || true
          echo "---- scripts ----" && ls -la scripts || true
          echo "---- cache/eod (before) ----" && ls -la cache/eod || true

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance

      - name: Verify Universe CSV exists & columns
        run: |
          test -f data/ind_nifty500list.csv || (echo "ERROR: data/ind_nifty500list.csv not found" && exit 1)
          python - << 'PY'
          import pandas as pd
          df = pd.read_csv("data/ind_nifty500list.csv")
          print("Universe columns:", list(df.columns))
          need = {"Company Name","Industry","Symbol","Series","ISIN Code"}
          missing = need - set(df.columns)
          if missing:
              raise SystemExit(f"ERROR: Universe CSV missing columns: {missing}")
          eq = df[df["Series"].astype(str).str.upper()=="EQ"].copy()
          eq["Symbol"] = eq["Symbol"].astype(str).str.strip().str.upper()
          print("Universe size (EQ only):", len(eq))
          print("First 10 symbols:", eq["Symbol"].head(10).tolist())
          eq[["Symbol","Series"]].head(10).to_csv(sys.stdout, index=False)
          PY

      - name: Quick test fetch (RELIANCE.NS + ^NSEI)
        run: |
          python - << 'PY'
          import yfinance as yf
          print("RELIANCE.NS last 3 rows:")
          print(yf.download("RELIANCE.NS", period="5d").tail(3))
          print("\nIndex ^NSEI last 3 rows:")
          print(yf.download("^NSEI", period="5d").tail(3))
          PY

      - name: Probe first 5 symbols individually (write temp)
        run: |
          python - << 'PY'
          import os, pandas as pd, yfinance as yf
          df = pd.read_csv("data/ind_nifty500list.csv")
          df = df[df["Series"].astype(str).str.upper()=="EQ"].copy()
          syms = df["Symbol"].astype(str).str.strip().str.upper().unique().tolist()[:5]
          os.makedirs("cache/eod", exist_ok=True)
          ok = 0
          for s in syms:
            yf_sym = f"{s}.NS"
            d = yf.download(yf_sym, period="3mo")
            if d is None or d.empty: 
              print(f"FAIL {s}: no data from yfinance ({yf_sym})"); 
              continue
            d = d.rename_axis("Date").reset_index()[["Date","Open","High","Low","Close","Volume"]]
            d["Date"] = pd.to_datetime(d["Date"]).dt.date.astype(str)
            out = f"cache/eod/{s}.csv"
            d.to_csv(out, index=False)
            print(f"OK  {s}: wrote {len(d)} rows -> {out}")
            ok += 1
          print(f"Probe result: {ok}/{len(syms)} wrote files")
          PY

      - name: Run full updater (writes cache/eod/*.csv)
        env:
          UNIVERSE_CSV: data/ind_nifty500list.csv
          DATA_CACHE_DIR: cache/eod
          INDEX_SYMBOL: NIFTY50
          DAYS_BACK: 1200
        run: |
          python scripts/update_eod.py

      - name: List generated files (after)
        id: list_files
        run: |
          echo "---- cache/eod (after) ----"
          mkdir -p cache/eod
          count=$(find cache/eod -maxdepth 1 -type f -name "*.csv" | wc -l)
          echo "CSV_COUNT=$count" >> $GITHUB_OUTPUT
          find cache/eod -maxdepth 1 -type f -name "*.csv" | head -30
          test -f cache/eod/NIFTY50.csv && head -5 cache/eod/NIFTY50.csv || true

      - name: Fail if no CSVs were produced
        if: steps.list_files.outputs.CSV_COUNT == '0'
        run: |
          echo "ERROR: No CSVs were produced in cache/eod/"
          exit 1

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f cache/eod/*.csv || true
          git commit -m "chore: update EOD cache [skip ci]" || echo "No changes to commit"
          git push
